Feat/rights check
xi-effect/xi.backend pull request #173
Opened 2022-12-28 03:14 UTC by Exllent

2022-12-29 16:49 UTC, porebrikk commented on xieffect/test/communities/conftest.py
> +        community_participant_id: int,
Будто бы избыточное название. Почему не community_id?

2022-12-29 16:49 UTC, porebrikk commented on xieffect/test/communities/base/invites_test.py
> +    last_participant_id(create_community=True)
Зачем?

2022-12-29 16:49 UTC, porebrikk commented on xieffect/test/communities/base/roles_test.py
> +    print(get_roles_list(client, test_community))
:)

2022-12-29 16:49 UTC, porebrikk commented on xieffect/test/communities/conftest.py
> +    return wrapper
Не понимаю, что тут происходит с сообществами и зачем.

2022-12-29 16:49 UTC, porebrikk commented on xieffect/test/communities/services/news_test.py
> +        community_participant_id=last_participant_id(create_community=True),
Почему не тестовый номер сообщества?
Вопрос не только к этой строчке.

2022-12-29 20:57 UTC, Exllent commented on xieffect/communities/base/__init__.py
>  from .roles_rst import controller as role_namespace
Я полностью согласен, что порядок нарушен, но если сделать всё по порядку будет ошибка циркулярных импортов

2022-12-29 21:14 UTC, Exllent commented on xieffect/test/communities/conftest.py
> +        community_participant_id: int,
create_participant_role(permission_type=..., community_participant_id=last_participant_id())
по моему мнению если сделать community_id то тогда почему в этот параметр в некоторых тестах принимает
last_participant_id(), моё название, по моему мнению даёт понять что принимается не только как community_id ещё и как participant_id

2022-12-29 21:20 UTC, Exllent commented on xieffect/test/communities/base/invites_test.py
> +    last_participant_id(create_community=True)
по название не понятно может быть, но для того чтобы создать новое community, выше в тесте создаются новые участники, без community

2022-12-29 21:31 UTC, Exllent commented on xieffect/test/communities/conftest.py
> +    return wrapper
я здесь создаю новое community, для чего я это делаю и почему не использую, готовое решение, я создаю community для того чтобы, когда в тестах создаётся участник я создаю к нему community чтобы в дальнейшем использовать новое community.id и нового participant в связке, создавая роль на новое community & participant и наделяя это роль нужными правами, а если я буду использовать использовать test_community- фикстуру, тогда юзанётся Community.create где прописано добавление участника нового участника, который будет лишним

2022-12-29 21:39 UTC, Exllent commented on xieffect/test/communities/services/news_test.py
> +        community_participant_id=last_participant_id(create_community=True),
можно и тестовый номер сообщества, но last_participant_id здесь, нужно больше для того чтобы создать сообщество, можно конечно вынести это и написать test_community, но это добавит лишнюю строку

2022-12-29 21:40 UTC, Exllent commented on xieffect/test/communities/services/news_test.py
> +        community_participant_id=last_participant_id(create_community=True),
всё равно что тестовый номер сообщества что это, данные возвращают одинаковые

2022-12-30 11:52 UTC, porebrikk commented on xieffect/communities/base/__init__.py
>  from .roles_rst import controller as role_namespace
А вообще эти импорты необходимы?

2022-12-30 11:54 UTC, porebrikk commented on xieffect/test/communities/conftest.py
> +        community_participant_id: int,
К слову, я так же не понимаю, почему в некоторых тестах туда передается идентификатор участника, если это поле идет в Role.create в качестве community_id
Похоже на костыль

2022-12-30 12:02 UTC, niqzart commented on xieffect/communities/base/__init__.py
>  from .roles_rst import controller as role_namespace
Если порядок импортов вызывает цикл значит импорты неправильные

2022-12-30 12:03 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +    return wrapper
+ не называйте вложенные функции недескриптивно, wrapper это мало, дебажить потом будет невозможно

2023-01-05 16:56 UTC, porebrikk commented on xieffect/test/communities/base/roles_test.py
> +    socketio_client2.assert_only_received("update_role", successful_data)
Очень бросается в глаза повтор кода.

2023-01-05 16:56 UTC, porebrikk commented on xieffect/test/communities/base/roles_test.py
> +    second_update_role_data.pop("color")
Выглядит очень странно, как будто бы двойная работа, которую можно избежать написав изначально отдельный дикт с идентификаторами сообщества и роли и при необходимости использовать его как отдельный дикт или составную часть для того же update_role_data

2023-01-05 16:56 UTC, porebrikk commented on xieffect/test/communities/conftest.py
> +            participant_id -= 1
А почему здесь так?

2023-01-05 17:05 UTC, Exllent commented on xieffect/test/communities/conftest.py
> +            participant_id -= 1
Именно когда используется это разрешение юзается участник с Id=16, но последний участник выдаёт с Id=17, а community_id которое получает функция равно 14

2023-01-05 17:11 UTC, Exllent commented on xieffect/communities/base/roles_db.py
> +class ParticipantRole(Base):  # TODO pragma: no cover
Забыл

2023-01-10 19:31 UTC, porebrikk commented on xieffect/test/communities/conftest.py
> +            participant_id -= 1
Подстраивание фикстуры под определенные значения теста выглядят на мой взгляд странновато
Лучше сделать фикстуру более универсальной, чтобы ее результаты были предсказуемы независимо от контекста использования

2023-01-11 19:31 UTC, porebrikk commented on xieffect/communities/base/meta_db.py
> +            user_id=user_id
Тут должна быть запятая

2023-01-12 06:41 UTC, porebrikk approved these changes

2023-01-14 14:39 UTC, niqzart requested changes

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/invitations_db.py
>              community_id=community_id,
Я не понимаю, зачем делать изменения не по задаче. В задаче же нет "убрать все использования старых ролей". Это другая задача. Изменений в приглашениях вовсе быть не должно было

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/invitations_rst.py
> +    @check_participant(controller, permission=PermissionType.MANAGE_INVITATIONS)
Вот эта строка единственная, что должна была поменяться

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/invitations_sio.py
> +        invitation = Invitation.create(community.id, limit, days)
Снова не по задаче

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/meta_db.py
> +        participant = Participant(user=creator)
Туда же, не по задаче

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/meta_db.py
> -
Это часть задачи https://xi.kaiten.ru/space/90440/card/8337685

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/meta_db.py
>          )
Это от задачи https://xi.kaiten.ru/space/90440/card/7923155

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +        )
Выглядит неэффективно... Надо бы обсудить в дискорде

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/roles_sio.py
> +            for permission in received_permissions - permissions_from_db:
Вызовы методов были куда более читабельными

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/utils.py
> +        for per in ParticipantRole.get_permissions_by_participant(participant_id)
1. per это плохое имя переменной
2. зачем доставать все пермишны, если проверить надо ток 1? 
3. 
*вот почему мне казался тот запрос неэффективным*

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/utils.py
> +    )
1. per это плохое имя переменной
2. зачем доставать все пермишны, если проверить надо ток 1? 

*вот почему мне казался тот запрос неэффективным*

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/utils.py
> +    permission: PermissionType = None,
Дефолт None? Какой в этом смысл?

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/base/utils.py
> +
А тут неиспользуемый дефолт None портит всю картину

2023-01-14 14:39 UTC, niqzart commented on xieffect/communities/services/videochat_sio.py
>          ]
Красивое

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +        assert dict_equal(invite, invite_data, "limit")
Не по заданию

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +    )
Ничего не делает, не должно быть в PRе

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +        )
Смены форматирования кода, не относящегося к задаче не должны быть в PRе, это портит git blame

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +        )
Снова форматирование

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +    invite_id1, code1 = create_invite({})
Снова (и не только тут, но и дальше в этом тесте) не по заданию

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +    )
Форматирование

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +    }
Форматирование + не по заданию

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +    )
Форматирование

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +        ("delete_invite", delete_data),
Форматирование

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/invites_test.py
> +    )
Форматирование

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/meta_test.py
> +@mark.order(1001)
?

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/roles_test.py
> +    successful_role_data = {**role_data}
Красивое

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/roles_test.py
> +        )
Форматирование

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/base/roles_test.py
> +        if data["id"] == 1:
Равенство на id опять? Я же писал об этом

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +    return create_permission_wrapper
Относится к заданию?

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +    return create_permission_wrapper
Зачем нужно заменять 1 строку 8ю?

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/services/news_test.py
> +
Зачем строчка?

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/services/tasks_test.py
> +@mark.order(1011)
Нумерация неправильная. Не надо номеровать, если не знаете как

2023-01-14 14:39 UTC, niqzart commented on xieffect/test/communities/services/videochat_test.py
> +    )
Зачем?

2023-01-18 16:19 UTC, niqzart commented on xieffect/test/communities/services/news_test.py
> +
!

2023-01-18 16:19 UTC, niqzart commented on xieffect/test/communities/services/tasks_test.py
> +@mark.order(1011)
!

2023-01-19 19:51 UTC, niqzart approved these changes

2023-06-04 15:12 UTC, LuK050 commented on xieffect/communities/base/roles_db.py
> +    def delete_by_ids(cls, role_id: int, permissions_type: set[str]) -> None:
Хм, мне кажется довольно странным и неудобным принимать множество как аргумент. Если уж оно нужно для быстрого поиска, то почему бы не принимать `Iterable`, как и в остальных функциях, а уже в функции преобразовывать его в множество?

2023-06-04 18:28 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +    def delete_by_ids(cls, role_id: int, permissions_type: set[str]) -> None:
Я тоже не супер понимал, почему тут set-ы, проверю, логично ли избавиться

2023-06-04 18:40 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +    def delete_by_ids(cls, role_id: int, permissions_type: set[str]) -> None:
Нет, тут set экономит, ибо в единственном использовании метода сюда передаётся set, два раза конвертировать (сначала из set в list, потом обратно) будет странно

P.S. Iterable не является 100-валидной заменой `set`-а, всё же set-ы в своей основе беспорядочные и значительно быстрее для операций вроде `in`

2023-06-04 18:44 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +    def delete_by_ids(cls, participant_id: int, role_ids: set[int]) -> None:
В этом тоже в delete_by_ids получает set, потому что с сетами работают события `update_participant` и `update_role` (там вычитание, т.е. разница множеств, она значительно быстрее на set-ах). А в create_bulk аргумент используется в for-each-цикле, поэтому там Iterable подходит по определению

2023-06-04 18:48 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +    def delete_by_ids(cls, role_id: int, permissions_type: set[str]) -> None:
Вообще может быть неплохой темой на краткий рассказ на первое бэк-чаепитие, что-нибудь про set/list

2023-06-04 19:20 UTC, LuK050 approved these changes

2023-06-04 19:22 UTC, LuK050 commented on xieffect/communities/base/roles_db.py
> +    def delete_by_ids(cls, role_id: int, permissions_type: set[str]) -> None:
> Нет, тут set экономит, ибо в единственном использовании метода сюда передаётся set, два раза конвертировать (сначала из set в list, потом обратно) будет странно
> 
> P.S. Iterable не является 100-валидной заменой `set`-а, всё же set-ы в своей основе беспорядочные и значительно быстрее для операций вроде `in`

Понимаю, просто привёл как пример по аналогии с другими функциями))

2023-06-11 09:33 UTC, niqzart approved these changes

2023-06-11 10:44 UTC, merged