Feat/menageming participants
xi-effect/xi.backend pull request #187
Opened 2023-03-25 20:53 UTC by Exllent

2023-03-26 04:12 UTC, porebrikk commented on xieffect/communities/base/meta_sio.py
А вообще стоит ли оставлять участников в ивентспейсе сообщетсва?
Например у тех же ролей, которые идут в той же стопке вкладок по фигме, свой ивентспейс...

2023-03-26 04:12 UTC, porebrikk commented on xieffect/communities/base/meta_sio.py
> +    @controller.database_searcher(Participant)
Мне казалось, что check_permission имеет под капотом серчер участника
Оно не работает без database_searcher'а?

2023-03-26 04:12 UTC, porebrikk commented on xieffect/test/communities/base/meta_test.py
> +    participant_data['role_ids'] = role_ids[1:]
Тоже выглядит как перспективное место для list out of range

2023-03-26 04:12 UTC, porebrikk commented on xieffect/test/communities/base/meta_test.py
> +
Лишняя пустая строка

2023-03-26 04:12 UTC, porebrikk commented on xieffect/test/communities/base/meta_test.py
> +
И вообще местами проскакивают двойные пустые строки в тесте между строками логически цельного кода
Осталось от принтов и проверок?

2023-03-26 16:18 UTC, niqzart commented on xieffect/communities/base/meta_db.py
> +
В ffs==0.4.11 этот класс называется ModBase, а сами методы мы вовсе прокидываем [в _core](https://github.com/xi-effect/xi.backend/blob/feat/menageming-participants/xieffect/common/_core.py#L99), но да, они должны работать

2023-03-26 16:18 UTC, niqzart commented on xieffect/communities/base/meta_db.py
> +        )
А ещё лучше использовать filter вместо where

2023-03-26 16:20 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
> +        participant_id: int
Там, вероятно, есть разница, то ли поля по-другому названы, толи из-за привязки к БД, но точно не скажу, может и можно упростить модели

2023-03-26 16:21 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +        )
filter вместо where можно и в delete (вроде как)

2023-03-26 16:24 UTC, niqzart commented on xieffect/test/communities/base/meta_test.py
> +    participant_id = get_participants_list(client, "")[0].get("id")
Вместо "" лучше прямо использовать None, мб даже прописать его дефолтом в той функции

2023-03-26 16:24 UTC, niqzart commented on xieffect/test/communities/base/meta_test.py
> +    result = check_code(
Если сделать, как я написал ниже, с `username: str | None = None`, то название начинает звучать логично

2023-03-26 16:26 UTC, niqzart commented on xieffect/communities/base/meta_rst.py
> +        return Participant.search_by_username(search, start, finish - start)
А ещё search может быть None

2023-03-26 19:54 UTC, Exllent commented on xieffect/communities/base/meta_db.py
> +        )
> Не вижу фильтра по сообществу. Оно выкатывает все записи в таблице Participant в случае пустого запроса?

да, в случае пустого запроса получает всех участников

2023-03-26 22:26 UTC, porebrikk commented on xieffect/communities/base/roles_db.py
> +        )
Да, можно

2023-03-26 22:38 UTC, Exllent commented on xieffect/communities/base/meta_sio.py
> +        )
я просто вычитаю разность из тех ролей которые пришли списком, те роли которые уже в бд

2023-03-26 22:39 UTC, Exllent commented on xieffect/communities/base/meta_sio.py
> +        )
принципе сделал всё также как и в role_update с разрешениями

2023-03-26 22:40 UTC, porebrikk commented on xieffect/communities/base/meta_sio.py
> +        )
Но у тебя же строчкой выше remove схождений полученных ролей с ролями бд 
Это не то же самое, что и вычитание?

2023-03-27 11:28 UTC, Exllent commented on xieffect/communities/base/meta_sio.py
> +        leave_room(self.room_name(community.id))
В тестах закрытие комнаты происходит после удаления участника, если добавить check_participant, тогда в декораторе падает ошибка, потому что участника нет

2023-04-02 17:38 UTC, niqzart requested changes
Пробежался по всему, кроме тестов, вот комменты на доделать. Старые комменты Дениса тоже нужно доотвечать, не всё пофикшено

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/__init__.py
> +from .meta_rst import controller as communities_namespace, second_controller as participants_namespace
Один контроллер на файл. Если их несколько, значит должно быть несколько файлов

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_db.py
> +            limit,
Дублирован вызов db.session.get_paginated, хотя можно было `join` и `filter` сделать в if-е, через `stmt = stmt.<...>`. Точно также, как в остальных _db файлах сделано

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_rst.py
> +second_controller = ResourceController("participants-meta", path="/communities/<int:community_id>/participants/")
А зачем вообще несколько контролеров? Тут же супер просто их объединить, и то, и то про meta

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
Всё ещё актуально. Без разделения на два ивентспейса принято не будет (и два разных файла соответственно)

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
> +            )
Это нужно делать одним запросом к БД, не кучей

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
> +        role_ids_from_db = set(
Лучшее название: current_role_ids

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
> +        role_ids_from_db = set(
Здесь и строчкой ниже нет типизации

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
> +            controller.abort(400, "Forbidden remove yourself")
Сообщение об ошибке ужасно, у нас где-то уже есть адекватное на такой случай

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/meta_sio.py
> +            controller.abort(400, "Forbidden remove yourself")
Нашёл, `Target is the source`

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +    MANAGE_PARTICIPANT = 5
PARTICIPANT**S**

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +        )
Не нужно реформатить нетронутый в задаче код. Нужно отменить эти изменения, и так куча конфликтов будет

2023-04-02 17:38 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +        )
Этот метод супер просто переделать на role_ids, используя встроенный метод колонки `cls.role_id.in_()` (или вроде того)

2023-04-03 10:30 UTC, porebrikk commented on xieffect/communities/base/meta_rst.py
> +    @controller.database_searcher(Community)
Мы с тобой точно такую же конструкцию поменяли на @check_participant(controller) в meta_sio

2023-04-03 10:30 UTC, porebrikk commented on xieffect/communities/base/roles_db.py
> +        )
А это не блейк?

2023-04-06 05:02 UTC, porebrikk commented on xieffect/communities/base/roles_db.py
> +    def delete_by_participant(cls, participant_id: int, role_ids: set[int]) -> None:
У тебя таблица ParticipantRole
У нее составной первичный ключ
Это не delete_by_participant
Мой старый комментарий по отношении к этому методу все еще актуален

2023-04-06 05:02 UTC, porebrikk commented on xieffect/communities/base/roles_db.py
> +        )
Все еще актуально

2023-04-06 05:03 UTC, porebrikk commented on xieffect/test/communities/base/meta_test.py
> +    participant_id = get_participants_list(client, "")[0].get("id")
Все еще актуально

2023-04-06 05:54 UTC, porebrikk commented on xieffect/communities/base/participants_sio.py
> +        )
Вот тут тоже вроде как удаляется participant, а метод delete_participant_role

2023-04-06 05:54 UTC, porebrikk commented on xieffect/communities/base/roles_db.py
> +    def delete_by_role(cls, role_id: int, permissions_type: set[str]) -> None:
Тут та же история, что и с ParticipantRole

2023-04-06 09:29 UTC, niqzart commented on xieffect/communities/base/roles_db.py
> +        )
Значения не имеет

2023-04-07 19:31 UTC, Exllent commented on xieffect/communities/base/participants_sio.py
> +        )
delete_participant занят в videochat_sio

2023-04-09 12:58 UTC, porebrikk approved these changes

2023-04-09 13:10 UTC, niqzart approved these changes

2023-04-09 13:13 UTC, merged