Meta: Discussion
xi-effect/xi.backend pull request #190
Opened 2023-05-04 07:30 UTC by porebrikk

2023-05-05 13:20 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +class MessageFile(Base):  # TODO: (==TaskEmbed) Mb an abstract class?
Вообще идея абстрактного класса очень неплохо. Но тогда стоит подумать, чтобы вынести туда максимум всего. Можно сейчас по-простому вынести, если хочешь, а потом заведём таску на рефактор

2023-05-05 13:20 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +class MessageFile(Base):  # TODO: (==TaskEmbed) Mb an abstract class?
Ток тогда с названиями функций аккуратнее

2023-05-05 13:20 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +    __tablename__ = "message_files"
Я бы помечал, что это про дискуссии, префиксом `ds_`, например (но лучше что мемное придумать, как Коммунальные Услуги)))

2023-05-05 13:20 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        self.pinned = not self.pinned
Очень странный метод. Называется "закрепить", а на самом деле открепляет, если не угадал. Вообще мало смысла в нём, можно же просто `message.pinned = True/False` прямо в контроллерах прописывать

2023-05-05 13:20 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        db.session.commit()
Зачем commit? Он автоматически делается в любом контроллере

2023-05-05 13:20 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        return self
Зачем возвращать self?

2023-05-05 13:20 UTC, niqzart commented on xieffect/test/communities/base/discussion_test.py
> +    updated_message: DiscussionMessage = message.update(new_content, [new_file_id])
Можно же просто дальше пользоваться объектом message...

2023-05-05 13:20 UTC, niqzart commented on xieffect/test/communities/base/discussion_test.py
> +    assert updated_message.pinned is not message_status
Проверка ни о чём, проверяем по сути работает ли ORM-ка. Этот кусок спрашивает: если я изменю поле .pinned в объекте message, оно изменится? Что-то аналогичное:
```py
d = {"a": 3}
d["a"] = 2
assert d["a"] == 2
```

2023-05-05 13:25 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        self.pinned = not self.pinned
Представляем контроллер. В него приходит событие "message-pin". Дальше... Если сообщение уже закреплено, то вызов .pin() нам не подойдёт в чистом виде, придётся творить такое:
```py
if message.pinned:
  # кидаем ошибку? просто return?
else:
  message.pin()
```

2023-05-06 00:53 UTC, porebrikk commented on xieffect/communities/base/discussion_db.py
> +    __tablename__ = "message_files"
Ну DS, к слову, тоже достаточно распространенная аббревиатура (Downspout, Down Syndrome, Direct Support)
Но можно и DISC, например

2023-05-08 10:47 UTC, niqzart commented on xieffect/common/abstract.py
> +    __abstract__ = True
Методы этого класса полагают, что есть колонка file_id, но её в абстрактном классе нет. Вроде нет причин, почему бы её не добавить прямо сюда, ещё и строчку повторяющуюся уберём

2023-05-09 08:38 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        files: list[int] = [] if files is None else files
Можно None, но дефолт не None

mypy (когда мы его добавим) будет кричать на `files: list[int]` как на объявление переменной во второй раз. В питоне так преобразование переменных в новый тип, кстати, не работает. Используется первый заданный тип

Бонус: `files or []` эквивалентно `files if files else []`, можно использовать короткую версию, которую можно вовсе поместить в строчку с вызовом `add_files`

2023-05-09 08:38 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +    files = relationship("File", secondary=MessageFile.__table__)
Нужно ли здесь passive_deletes=True?

2023-05-09 08:40 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        self.content = self.content if content is None else content
Очень странное, мы делаем действие, даже если оно не нужно. Лучше с нормальным if-ом

2023-05-09 08:40 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        return db.get_first(select(cls).filter(cls.id == entry_id))
find_first_by_kwargs?

2023-05-09 08:40 UTC, niqzart commented on xieffect/communities/tasks/main_db.py
> -    FileModel = PydanticModel.nest_flat_model(File.FullModel, "file")
Эта модель не использовалась?

2023-05-09 08:41 UTC, niqzart commented on xieffect/communities/tasks/main_db.py
> -    FileModel = PydanticModel.nest_flat_model(File.FullModel, "file")
А, она теперь не используется, понято

2023-05-09 08:41 UTC, niqzart commented on xieffect/communities/tasks/main_db.py
Тоже, нужно ли passive_deletes=True оставить?

2023-05-09 09:02 UTC, porebrikk commented on xieffect/communities/base/discussion_db.py
> +    files = relationship("File", secondary=MessageFile.__table__)
Да, думаю, что нужно

2023-05-09 09:02 UTC, porebrikk commented on xieffect/communities/tasks/main_db.py
+

2023-05-09 09:19 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        files: list[int] = None,
Если переменная может быть None (а эта может быть), то стоит так и указывать. Меньше рефакторинга делать нужно будет, когда добавим mypy

2023-05-09 09:28 UTC, niqzart approved these changes

2023-06-12 10:26 UTC, niqzart requested changes

2023-06-12 10:26 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +            MessageFile.add_files(set(files) - old_files, message_id=self.id)
Два раза конвертируется список files в set, лучше вынести

2023-06-12 10:26 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +    def update(self, content: dict | None, files: list[int] | None) -> None:
Это не файлы, это file_ids

2023-06-12 10:26 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +    )
Кажется, лучше не прописывать и условие на ForeignKey и условие на relationship

2023-06-12 10:26 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +    )
Но сообщений же может быть миллион, крайне странная модель

2023-06-12 10:26 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        return cls.find_paginated_by_kwargs(offset, limit, id=entry_id)
offset и limit при получении дискуссии, причём с idшником? Мб имелись ввиду сообщения?

2023-06-12 10:26 UTC, niqzart commented on xieffect/communities/base/discussion_db.py
> +        return cls.find_paginated_by_kwargs(offset, limit, id=entry_id)
Бонус: дефолты особо полезными тут не считаю

2023-06-12 10:26 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +            "description",
kwarga-ами читается лучше

2023-06-12 10:26 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +    return {"test": "content"}
В тестах всё тестовое, не нужно в названии фикстур это упоминать

2023-06-12 17:21 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +) -> int:
Это тоже в тестах и тоже test_ лишнее))

2023-06-12 17:43 UTC, niqzart approved these changes

2023-06-12 17:56 UTC, merged