Feat/tests base
xi-effect/xi.backend pull request #194
Opened 2023-05-29 20:02 UTC by mikeGot

Основа для тестов:

- [ ]  БД Test и Question
- [ ] TestsEventSpace и QuestionsEventSpace
- [ ] 2 ручки на тесты
- [ ] Автотесты на tests и questions

2023-05-29 20:05 UTC, mikeGot commented on xieffect/communities/tasks/tests_sio.py
> +        community: Community,  # noqa: U100
Здесь noqa сделал временно, чтобы pre-commit пропустил. Пока не разобрался нужен ли здесь community и check_participant..

2023-05-30 11:22 UTC, porebrikk commented on xieffect/communities/tasks/tests_sio.py
> +        pass
И здесь тоже можно DeleteModel

2023-05-30 11:22 UTC, porebrikk commented on xieffect/test/communities/conftest.py
> +    return test.id
Ты прав, название странное)

2023-06-01 21:02 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +        test_id: int
А почему бы просто не унаследовать эту модель от `TasksEventSpace.CommunityIdModel`? Вроде нигде `test_id` не используется без `community_id`

2023-06-01 21:03 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +class QuestionsEventSpace(EventSpace):
Хорошо бы в отдельный файл второй Space. Контроллер тоже можно отдельный

2023-06-01 21:05 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +        pass
Мне лично страшно))
Как бы сократить количество моделей. По сути TestIdModel и так должна содержать `community_id`, можно и не уточнять это в названии

2023-06-01 21:10 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +        text: str = None
Кажется, из-за этого дока поехала. Проблема в том, что если бы это было сделано через модели, которые на БД основаны, то там было бы конвертирование в строки, а тут с клиента будет требоваться число, что не торт. Можно это всё же в БД-модель сложить?

2023-06-04 10:23 UTC, mikeGot commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        "kind": "detailed",
Вроде я строку передаю, а не число

2023-06-04 10:24 UTC, mikeGot commented on xieffect/communities/tasks/tests_sio.py
> +        text: str = None
https://github.com/xi-effect/xi.backend/pull/194/files#r1216516747

2023-06-04 19:56 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        "kind": "detailed",
Тесты тут совершенно не при делах. TypeEnum сам по себе завязан на int-ах, если его использовать через Pydantic. Как оно работает — не знаю, но как факт, дока не работает

2023-06-05 20:02 UTC, porebrikk commented on xieffect/communities/tasks/questions_sio.py
> +    def open_questions(self, test: Test):
close_questions аналогично

2023-06-05 20:04 UTC, porebrikk commented on xieffect/communities/tasks/questions_sio.py
> +        question_id: int
Используется только в связке с TestIdModel, так что тоже можно было бы сразу унаследовать от него

2023-06-05 20:26 UTC, porebrikk commented on xieffect/communities/tasks/tests_teacher_rst.py
> +    )
dest одинаковые

2023-06-05 20:30 UTC, porebrikk reviewed
Посмотрел все, кроме tests_teacher_test.py

2023-06-05 20:30 UTC, porebrikk reviewed
Посмотрел все, кроме tests_teacher_test.py

2023-06-06 10:48 UTC, mikeGot commented on xieffect/communities/tasks/questions_sio.py
> +            controller.abort(400, "Validation error in kind")
```
        kind: str = kwargs.get("kind")
        if kind:
            kind_enum: QuestionKind = QuestionKind.from_string(kind)
            if kind_enum:
                kwargs["kind"] = kind_enum
            else:
                controller.abort(400, "Validation error in kind")
```
Такой код более понятный? Просто если избавляться от if в if-e, то это только вынося часть кода в отдельную функцию, как мне кажется

2023-06-06 11:02 UTC, mikeGot commented on xieffect/communities/tasks/tests_sio.py
> +    class CreationModel(Test.CreateModel, TasksEventSpace.CommunityIdModel):
Вот здесь используется CommunityIdModel без TestIdModel, поэтому не стал наследовать TestIdModel(TasksEventSpace.CommunityIdModel)

2023-06-08 20:14 UTC, niqzart commented on xieffect/communities/tasks/questions_sio.py
> +            controller.abort(400, "Validation error in kind")
Решение Дениса получше, но `kind_enum` это плохое название для переменной. Лучше `raw_kind` для строки (и тип у неё `str | None`) и `kind: QuestionKind | None`

2023-06-13 13:38 UTC, mikeGot commented on xieffect/communities/tasks/questions_sio.py
> +        if test.community_id != community.id:
Если я правильно все понял, то и здесь (в questions) нам эту проверку тоже надо делать, не только в Task(Test)

2023-06-13 15:39 UTC, LuK050 requested changes

2023-06-13 15:39 UTC, LuK050 commented on xieffect/communities/tasks/tests_sio.py
> +        files: list[int] = []
Если я не ошибаюсь, изменяемый тип в качестве дефолтного значения довольно плохая практика как в функциях, так и в классах. Думаю, лучше сделать `files: list[int] | None = None`

2023-06-13 15:39 UTC, LuK050 commented on xieffect/test/communities/tasks/question_test.py
> +# def test_
Не думаю, что в этом есть необходимость))

2023-06-13 16:57 UTC, mikeGot commented on xieffect/communities/tasks/tests_sio.py
> +        files: list[int] = []
ты наверное про вот  [эту вещь](https://web.archive.org/web/20200221224620id_/http://effbot.org/zone/default-values.htm). Но, насколько я понял, что это только если в качестве параметров функции/класса передавать mutable, а вот если в самой функции, то такого вроде бы не должно быть

2023-06-13 19:01 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +        files: list[int] = []
Не, это не про параметры функции, оно реально везде проблемное... но конкретно в Pydantic-е от этого есть защита через deep-copy, поэтому всё ок

2023-06-16 09:28 UTC, niqzart requested changes
Как-то так, пока хватит. Если следующие ревьюеры смогут по моему ревью также чекать, решены ли комменты, будет шедевр

2023-06-16 09:28 UTC, niqzart commented on xieffect/communities/tasks/tests_db.py
> +        ForeignKey("cs_tests.id", ondelete="CASCADE", onupdate="CASCADE"),
Теперь актуально [сообщение](https://discord.com/channels/706806130348785715/897109928177696768/1119190158244319263)

2023-06-16 09:28 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +            return super().dict(*args, **kwargs)
Выделить бы всё это в одну модель в базовом SIO-классе, без наследования от объекта idшников, а затем сделать `UpdateTaskModel` и `UpdateTestModel`, примерно так:
```py
class UpdateTestModel(UpdateModel, TestIdModel):
    pass
```

2023-06-16 09:28 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +            return super().dict(*args, **kwargs)
(к другим моделям тоже может относится)

2023-06-16 09:28 UTC, niqzart commented on xieffect/communities/tasks/tests_sio.py
> +    @controller.argument_parser(DeleteModel)
Может, просто `@controller.argument_parser(TestIdModel)`?

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +    def test_maker_inner() -> (Test, int):
Странный return-type, что ето

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_success("update_question", updated_data)
Не хватает `expected_data` и лучше kwarg-ами, как везде

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_success("update_question", updated_data)
Хм, а в update_question вроде force_ack вместо возврата вопроса. Как бы рабочая схема, но что если в будущем сервер будет не просто сохранять, а как-то обрабатывать данные и после сохранения пользователю надо что-то вернуть. В проекте же в основном схема с ack-ами

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack("update_question", updated_data, expected_code=400)
надо проверять сообщение от сервера + лучше kwarg-ами

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +    )["id"]
Будто бы не первая такая фикстура, её вроде копировать не надо, они же глобальные

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +def assert_create(
Нейминг, не понятно, что создаётся

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +class TestTeacherCrud:
Класс тут смысловой нагрузки не несёт

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        assert_create(socketio_client, test_data, "new_test")
А факт создания теста тут как-то используется?

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack("update_question", updated_data, expected_code=400)
Тоже самое в тестах

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_success("update_question", updated_data)
Тоже самое в тестах

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +            ),
dict, кажется, лишнее

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +)
Сложное, может в раздельные тесты?

2023-06-16 09:28 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +def test_task_sio_errors(
task?

2023-06-16 12:02 UTC, mikeGot commented on xieffect/test/communities/tasks/question_test.py
> +    )
Если expected_data использовать, то нужно все параметры передавать (я так понял), а вот expected_json проверяет что есть

2023-06-16 19:29 UTC, niqzart commented on xieffect/communities/tasks/questions_sio.py
> +    ):
Лучше прочитать [коммент про ack-и](https://github.com/xi-effect/xi.backend/pull/194#discussion_r1232001110). А так да, функция в питоне не может ничего не вернуть, либо что-то, либо None

2023-06-17 10:32 UTC, mikeGot commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +)
Тогда и такое же тестирование Tasks нужно разделять, чтоб более-менее однообразно было

2023-06-17 11:31 UTC, mikeGot commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +class TestTeacherCrud:
Может все таки оставить? Проще разобраться и понять какие именно тесты нужны (свернуть ненужные в IDE) А после разбивки https://github.com/xi-effect/xi.backend/pull/194#discussion_r1232011394 может иx тоже в отдельный класс добавить?

2023-06-17 11:33 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +class TestTeacherCrud:
Если есть проблема навигации и хочется сворачивать вещи, то это сигнал к тому, что файл слишком большой, сворачивание элементов это костыль

2023-06-17 11:34 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +class TestTeacherCrud:
Плюс эти тесты не сгруппированы по смыслу, create всё же сильно отличается от read, update и delete

2023-06-17 11:34 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +)
Угу

2023-06-17 11:45 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    )
А я не про client.get, я про `socketio_client.assert_emit_success`

2023-06-17 15:13 UTC, mikeGot commented on xieffect/communities/tasks/tests_db.py
> +                setattr(test, key, value)
я пока не смог найти ответ, почему этот вариант рабочий, а если наследовать, то нет. Подозреваю, что может быть дело в наследовании классов sqlalchemy. Вот такая ошибка при update ` sqlalchemy.exc.CompileError: Unconsumed column names: description, name`

2023-06-17 19:59 UTC, niqzart commented on xieffect/communities/tasks/tests_db.py
> +                setattr(test, key, value)
А, ну да, точно, в Task же сделано через прямое обновление, а не через ORM, что работает вообще по-другому. А вот если вот этот Test.update положить на место Task.update, то всё работает, хорошо бы так и сделать, что то, что другое, 1 запрос к БД генерит

2023-06-17 20:10 UTC, niqzart commented on xieffect/communities/tasks/tests_db.py
> +                setattr(test, key, value)
Что я ещё не совсем понимаю, так это зачем этой штуке быть @classmethod, если в любом случае приходится искать таску, причём, получается, дважды, ибо место, откуда вызывается `update` уже и так вытащило эту таску из БД

2023-06-18 10:19 UTC, mikeGot commented on xieffect/communities/tasks/tests_db.py
> +                setattr(test, key, value)
> Что я ещё не совсем понимаю, так это зачем этой штуке быть @classmethod, если в любом случае приходится искать таску, причём, получается, дважды, ибо место, откуда вызывается `update` уже и так вытащило эту таску из БД

Предлагаешь передавать туда объект Test?

2023-06-18 10:42 UTC, mikeGot commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_success("update_question", updated_data)
> Хм, а в update_question вроде force_ack вместо возврата вопроса. Как бы рабочая схема, но что если в будущем сервер будет не просто сохранять, а как-то обрабатывать данные и после сохранения пользователю надо что-то вернуть. В проекте же в основном схема с ack-ами

То есть нужно вернуть обновленный Question?

2023-06-18 11:13 UTC, mikeGot commented on xieffect/communities/tasks/questions_sio.py
> +                controller.abort(400, "Validation error in kind")
> Обычно такие ошибки по-другому пишутся, лучше делать их близкими друг к другу по тексту

Ошибки валидации я не видел чтобы вручную обрабатывались, поэтому затрудняюсь в правильном написании description

2023-06-18 19:11 UTC, mikeGot commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack("update_question", updated_data, expected_code=400)
> надо проверять сообщение от сервера + лучше kwarg-ами

Интересно, почему лучше kwargs, если IDE сама подсказывает какие параметры нужны функции? А dict мы сами пишем без всяких подсказок

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    ids=["update_all_data", "partly_updated_data"],
"full" и "partial", лучше через `pytest.param`, как [тут](https://github.com/niqzart/carp-lang/blob/main/carp/tests/execution/test_control.py#L64-L81)

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    ids=["update_all_data", "partly_updated_data"],
updated_data_text это плохое название для переменной-словаря, просто `update_data` сойдёт

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        "expected_code": 200,
Это дефолт

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack(**data)
Просто kwarg-и можно использовать, тут переменная ни к чему

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    )
```suggestion
    updated_data: dict[str, Any] = {
        **question_ids,
        **updated_data_text,
    }
```

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    )
Ну и название неправильное, updated это уже обновлённое, а это data для обновления. Можно просто data, как раз вторая переменная в этом тесте не нужна

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    test_data: dict[str, int | str | list] = {
В тестах всё тестовое

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    test_data: dict[str, int | str | list] = {
Тоже Any

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +            data["kind"] = QuestionKind.CHOICE
Почти уверен, что оно прекрасно сработает строчкой и в БД

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +            data["kind"] = QuestionKind.CHOICE
А если всё же делать вложенную функцию (бррр), то называть подобающе, question_data_inner

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +def question_data(client_test_id: int) -> Callable[[bool], dict[str, Any]]:
И типизация, кстати, тоже неправильная, функция тут с дефолтом в первом аргументе. Реально не стоит делать это вложенной функцией

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_data=dict_cut(test_data, "kind", "text"),
То, что выдан id не проверяется

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_data=dict_cut(test_data, "kind", "text"),
Этот dict_cut вызывается несколько раз, хотя по сути `question_data(enum_to_str=True) == dict_cut(test_data, "kind", "text")`, можно question_data пользовать (ну + "id": int)

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_json=dict(questions=[dict_cut(test_data, "kind", "text")]),
```suggestion
        expected_json={"questions": [dict_cut(test_data, "kind", "text")]},
```

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    ids=["update_all_data", "partly_updated_data"],
Плюс "choice" это же изначальное значение

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_json=dict(questions=[dict_cut(test_data, "kind", "text")]),
(не только тут, литерал словаря (который {}) предпочтительнее в python)

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack(**data)
(не только тут)

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/conftest.py
> +    )["id"]
Это общая-общая фикстура, можно в основной conftest положить, даже выше communities

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +def test_data(base_user_id: int, community_id: int) -> dict[str, int | str | None]:
Any (и много где ещё)

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/conftest.py
> +    delete_by_id(test.id, Test)
Зачем нам две такие фикстуры от разных пользователей? Я собираюсь в ближайшем рефакторинге удалить фикстуры для base_user или test@test.test

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack("update_question", updated_data, expected_code=400)
kwarg-и тоже подсказывает, если использовать их напрямую, их плюсы:
- пофиг на порядок
- сразу понятно, в какой параметр кидаем какую инфу
- если вызываемая функция добавит ещё параметров, то ничего не сломается

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    socketio_client.assert_emit_ack("update_question", updated_data, expected_code=400)
kwarg-и, если что, это key-word arguments. Т.е. в строчке `socketio_client.assert_emit_ack(event_name="update_question", ...)` `event_name="update_question"` это и есть kwarg. Не `**kwargs` — это spread-синтаксис, другой концепт

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
Сюда применяются все комментарии про использование `expected_data`, про Any, про литерал словаря, про лишние переменные, про лишние функции, про нейминг

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
> +        expected_code=200,
Через kwarg-и

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
> +        expected_code=200,
expected_code=200 это дефолт

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
> +        expected_code=200,
Снова dict_cut кажется лишним, когда можно вынести в переменную name и description, затем использовать `data={**ids_data, **<новая переменная>}`

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
> +    socketio_client.assert_emit_ack(
Вау, это типизация элемента словаря? Как я мог такой шедевр не увидеть

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
> +        expected_code=200,
И во втором изменённом тут тесте также

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
Сюда применяются все комментарии про использование expected_data, про Any, про литерал словаря, про лишние переменные, про лишние функции, про нейминг

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/teacher_test.py
Бонус: тогда этот файл task_teacher_test

2023-06-22 21:37 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +)
Случилось ли это?

2023-06-23 18:47 UTC, mikeGot commented on xieffect/test/communities/conftest.py
Мне убрать в tasks/conftest.py только все для question и test? или для тасок тоже?

2023-06-23 18:52 UTC, mikeGot commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +)
> > Тогда и такое же тестирование Tasks нужно разделять
> 
> Случилось ли это?

Cлучилось. Это же outdated

2023-06-23 18:54 UTC, niqzart commented on xieffect/test/communities/conftest.py
Для тасок тоже

2023-06-23 18:55 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +)
Outdated значит наличие любых изменений рядом, даже пробелов

2023-06-23 19:07 UTC, mikeGot commented on xieffect/communities/tasks/questions_sio.py
> +                controller.abort(400, str(e))
> Если хочется сделать красиво через try-except (в чём мало смысла перед рефакторингом, лучше одинаково, так проще искать), то переменная вовсе не нужна, можно сразу в kwargs["kind"] складывать:
> 
> ```python
> try:
>     kwargs["kind"] = QuestionKind.validate(raw_kind)
> except ValueError as e:
>     controller.abort(400, str(e))
> ```

Не хотелось копировать текст ошибки, если вдруг поменяется, чтобы не менять в нескольких местах. Тем более validate не просто так создавался)

2023-07-15 06:38 UTC, mikeGot commented on xieffect/test/communities/tasks/question_test.py
> +        expected_data=dict_cut(test_data, "kind", "text"),
> Этот dict_cut вызывается несколько раз, хотя по сути `question_data(enum_to_str=True) == dict_cut(test_data, "kind", "text")`, можно question_data пользовать (ну + "id": int)

Не совсем, в question_data еще и  "test_id" есть

2023-07-18 09:24 UTC, niqzart commented on xieffect/communities/tasks/questions_sio.py
> +                    400, f"{raw_kind} is not a valid {QuestionKind.__name__}"
`{QuestionKind.__name__}` можно спокойно заменить на `QuestionKind` (без `{}`)

2023-07-18 09:24 UTC, niqzart commented on xieffect/communities/tasks/questions_sio.py
> +            controller.abort(404, Question.not_found_text)
!

2023-07-18 09:24 UTC, niqzart commented on xieffect/communities/tasks/questions_sio.py
> +            test_id=test.id,
!

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        pytest.param({"kind": "simple"}, id="update_partial_data"),
update и data лишние слова в названии, ибо это название показывается рядом с названием самого теста. full и partial достаточно

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    )
Давайте по максимуму всё в "одну строчку", тип так:
```suggestion
    socketio_client.assert_emit_ack(
        event_name="update_question",
        data={
            **question_ids,
            "text": "update",
            "kind": "choice11223",
        },
        expected_code=400,
        expected_message=f"{data['kind']} is not a valid QuestionKind",
    )
```

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +    )
Или не особо читается? Мне кажется так все на месте

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_data={**dict_cut(data, "kind", "text"), "id": int},
Мы сначала добавили в question_data community_id, потом отрезали... Тут можно так без изменения смысла:
```suggestion
        expected_data={**dict_cut(question_data, "kind", "text"), "id": int},
```

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_data={**dict_cut(data, "kind", "text"), "id": int},
И тогда можно будет убрать переменную data

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        event_name="update_question", data={**question_ids, **data}, expected_data=data
Для красоты можно тыкнуть запятую в конце этой строки, тогда black поделит её на 3 строчки

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        event_name="update_question", data={**question_ids, **data}, expected_data=data
Вообще я считаю это предпочтительным форматированием для `assert_emit_ack` и методов `client`-а

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/task_common_errors_test.py
> +    return request.param
Oh no, они нашли параметризацию фикстур)))
Кстати, их можно типизировать: https://github.com/niqzart/carp-lang/blob/main/carp/tests/translation/test_tranlator.py#L22-L30

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/task_common_errors_test.py
> +):
Это тест пермишнов, не про email. Что-то вроде `test_task_fail_with_foreign_user`?

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/task_common_errors_test.py
> +def test_task_fail_too_many_files(
```suggestion
def test_task_fail_with_too_many_files(
```

2023-07-18 09:24 UTC, niqzart commented on xieffect/test/communities/tasks/question_test.py
> +        expected_data=dict_cut(test_data, "kind", "text"),
Хммм, тут тогда вопрос, зачем test_id там есть, его же можно хранить отдельно, но пусть будет, всё равно новый коммент написал на этот счёт

2023-07-18 09:33 UTC, niqzart reviewed
Это не всё, я подробнее буду перепроверять, но там точно останутся только самые мелочные мелочи, на которые я начну забивать

2023-07-18 09:33 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        expected_data=dict_cut(updated_data, "name", "description"),
Кажется, лучше наоборот, name и description в переменной (и назвать update_data), а `data={**update_data, **test_ids_data}`. Тогда не нужен будет dict_cut

2023-07-18 09:33 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        expected_data=dict_cut(updated_data, "name", "description"),
Бонус: update_data можно сделать параметризированной

2023-07-18 09:33 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +    }
По аналогии с question_ids, _data тут лишнее

2023-07-18 09:33 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +    ).get("id")
1 раз используется?

2023-07-18 09:33 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +            **dict_cut(test_data, "name"),
Одно поле...
```suggestion
            "name": test_data["name"],
```

2023-07-18 09:33 UTC, niqzart commented on xieffect/test/communities/tasks/tasks_teacher_test.py
> +    }
По аналогии с question_ids, _data тут лишнее

2023-07-18 09:38 UTC, niqzart commented
Отметка для следующих ревью: все комменты по предыдущим ревью, кроме последнего (которое магией гитхаба разбилось на два) и коммента про декоратор quetion_finder, закрыты

2023-07-18 11:08 UTC, mikeGot commented on xieffect/test/communities/tasks/question_test.py
> +    )
а {data['kind']} откуда возьмем если data удалить?

2023-07-18 11:31 UTC, mikeGot commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        expected_data=dict_cut(updated_data, "name", "description"),
Имеется в виду параметризировать весь тест? Тут еще параметры:
1. event_name="update_test",
2. test_id
3. f"/communities/{test_community}/tests/{test_id}/"
Которые тоже нужно параметризировать для test/task
Есть ли вообще смысл в этом?

2023-07-18 11:32 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        expected_data=dict_cut(updated_data, "name", "description"),
Нет, конечно же, я про 1 переменную. Как full и partial в другом тесте

2023-07-18 11:57 UTC, niqzart commented on xieffect/test/communities/tasks/tests_teacher_test.py
> +        expected_data=dict_cut(updated_data, "name", "description"),
На будущее, по терминологии "параметризировать (весь) тест" — плеоназм, параметризируем мы тесты в любом случае. Куда полезнее говорить "параметризировать <что-то>", про конкретные параметры. Как я сказал, "параметризировать update_data", имея ввиду только эту переменную, ничего кроме. То, что предложил ты это а-ля "параметризировать task/test", "параметризировать домен" или ещё какое умное слово, которое я не могу вспомнить

2023-07-18 18:15 UTC, niqzart commented on xieffect/communities/tasks/utils.py
> +    user_question: bool = True,
user?))

2023-07-18 18:15 UTC, niqzart commented on xieffect/communities/tasks/utils.py
> +    user_question: bool = True,
Я тоже так постоянно случайно пишу))

2023-07-18 18:15 UTC, niqzart commented on xieffect/test/communities/tasks/conftest.py
> +def task_maker(test_data: dict[str, Any]) -> Callable[Task]:
Тогда оно task_data, потому что task это superclass test-а

2023-07-18 18:15 UTC, niqzart commented on xieffect/test/communities/tasks/conftest.py
> +def task_maker(test_data: dict[str, Any]) -> Callable[Task]:
Ну и раз мы тут, давай в этом файлике порядок поменяем, чтобы сверху вниз читалось: таски -> тесты -> base_user штуки

2023-07-18 18:15 UTC, niqzart commented on xieffect/test/communities/tasks/conftest.py
> +def task_maker(test_data: dict[str, Any]) -> Callable[Task]:
Ооо, кстати, `Callable[[], Task]` должно быть

2023-07-18 18:15 UTC, niqzart commented on xieffect/test/communities/tasks/tasks_teacher_test.py
> +    task_data: dict[str, int | str | list] = {
Оп, JSON тоже, надо сюда Any

2023-07-18 18:15 UTC, niqzart commented on xieffect/test/communities/tasks/tasks_teacher_test.py
> +    task_data: dict[str, int | str | list] = {
Кстати, можно сделать вложенным, оставив в переменной ток `name` (строку, не словарь)

2023-07-18 18:15 UTC, niqzart commented on xieffect/test/communities/tasks/tasks_teacher_test.py
> +    task_data: dict[str, int | str | list] = {
page_id, если что, можно везде хардкодить 1, оно потом на фикстуру заменится

2023-07-18 18:16 UTC, niqzart commented on xieffect/test/communities/tasks/tasks_teacher_test.py
> +    task_data: dict[str, int | str | list] = {
А можно и забить, просто Any сделать

2023-07-18 21:33 UTC, niqzart approved these changes

2023-08-06 09:57 UTC, merged